# Generated by Django 5.0.1 on 2024-01-19 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10, verbose_name='Номер места')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.screening')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.user')),
            ],
        ),
    ]
