# Generated by Django 5.0.1 on 2024-01-22 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='room_number',
        ),
        migrations.AddField(
            model_name='room',
            name='rows',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='room',
            name='seats_per_row',
            field=models.PositiveIntegerField(default=17),
        ),
        migrations.AddField(
            model_name='screening',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='films.room', verbose_name='Зал'),
        ),
    ]
